<?php 
return array (
  'site_name' => '集货地源码',
  'site_title' => '集货地论坛为您提供 小猪V7.0源码出售',
  'site_logo' => 'http://weixin.jihuodi.com/uploads/e/ekfdng1401977502/3/e/d/3/thumb_53ddf1fd4c4b4.png',
  'site_url' => 'http://wxw.zealdream.com',
  'site_my' => 'Alex',
  'server_key' => '',
  'server_topdomain' => '',
  'connectout' => '',
  'ischeckuser' => 'true',
  'reg_needmp' => 'true',
  'reg_groupid' => '4',
  'reg_validdays' => '200',
  'router_key' => '',
  'ipc' => '',
  'site_qq' => '',
  'site_mp' => '',
  'baidu_map_api' => '22bb7221fc279a484895afcc6a0bb33a',
  'site_email' => '',
  'keyword' => '',
  'content' => '',
  'countsz' => '',
  'copyright' => '',
);