<?php 
return array (
  'site_name' => 'ZealDream',
  'site_title' => 'ZealDream微信平台',
  'site_logo' => 'http://wxw.zealdream.com/uploads/a/admin/d/e/9/7/thumb_540c4bf09c5ce.gif',
  'site_url' => 'http://wxw.zealdream.com',
  'site_my' => '小飞',
  'server_key' => '',
  'server_topdomain' => '',
  'connectout' => '',
  'ischeckuser' => 'true',
  'reg_needmp' => 'true',
  'reg_groupid' => '4',
  'reg_validdays' => '200',
  'router_key' => '',
  'ipc' => '',
  'site_qq' => '2334265543',
  'site_mp' => '',
  'baidu_map_api' => '22bb7221fc279a484895afcc6a0bb33a',
  'site_email' => '',
  'keyword' => '',
  'content' => '',
  'countsz' => '',
  'copyright' => 'ZealDream 版权所有',
);